
############################
# VISUALIZATION PARAMETERS #
############################
#/control/execute visu.mac
/vis/disable

#########################
# SET MATERIAL DATABASE #
#########################
/gate/geometry/setMaterialDatabase GateMaterials.db

#########
# WORLD #
#########
/gate/world/geometry/setXLength 50. cm
/gate/world/geometry/setYLength 50. cm
/gate/world/geometry/setZLength 50. cm
/gate/world/setMaterial Air

#######################################
# CT scanner for small animal imaging #
# 150x200 pixels                      #
# size of pixels : 0.5x0.5x1.0 mm3    #
# pixels are made up of silicon       #
#######################################
####################
# CTscanner system #
####################
/gate/world/daughters/name CTscanner
/gate/world/daughters/insert box
/gate/CTscanner/placement/setTranslation 0. 0. 150.5 mm
/gate/CTscanner/geometry/setXLength 50. mm
/gate/CTscanner/geometry/setYLength 50. mm
/gate/CTscanner/geometry/setZLength 1. mm
/gate/CTscanner/setMaterial Air
/gate/CTscanner/vis/forceWireframe
/gate/CTscanner/vis/setColor white

#############           ############
# CTSCANNER #   ---->   #  MODULE  #
#############           ############
/gate/CTscanner/daughters/name module
/gate/CTscanner/daughters/insert box
/gate/module/geometry/setXLength 50. mm
/gate/module/geometry/setYLength 50. mm
/gate/module/geometry/setZLength  1. mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white


############            ###########
#  MODULE  #    ---->   # PIXEL_0 #
############            ###########
/gate/module/daughters/name pixel
/gate/module/daughters/insert box
/gate/pixel/geometry/setXLength 50. mm
/gate/pixel/geometry/setYLength 50. mm
/gate/pixel/geometry/setZLength 1. mm
/gate/pixel/setMaterial Silicon
/gate/pixel/vis/setColor red

# ATTACH SYSTEM
/gate/systems/CTscanner/module/attach module
/gate/systems/CTscanner/pixel_0/attach pixel

# ATTACH LAYER
/gate/pixel/attachCrystalSD

###################################
# phantom in rotation (1 deg/s) : #
#  * 1 water cylinder             #
#  * 4 balls                      #
###################################
##################
# Water Cylinder #
##################
/gate/world/daughters/name waterCylinder
/gate/world/daughters/insert cylinder
/gate/waterCylinder/geometry/setRmin 0. mm
/gate/waterCylinder/geometry/setRmax 8. mm
/gate/waterCylinder/geometry/setHeight 20. mm
/gate/waterCylinder/placement/setRotationAxis 1 0 0
/gate/waterCylinder/placement/setRotationAngle 90. deg
/gate/waterCylinder/setMaterial Water
/gate/waterCylinder/vis/forceWireframe
/gate/waterCylinder/vis/setColor cyan

###################
# Aluminium Balls #
###################
/gate/waterCylinder/daughters/name aluminiumBall
/gate/waterCylinder/daughters/insert sphere
/gate/aluminiumBall/placement/setTranslation 4.76314 -2.75 -6. mm
/gate/aluminiumBall/geometry/setRmin 0. mm
/gate/aluminiumBall/geometry/setRmax 1. mm
/gate/aluminiumBall/setMaterial Aluminium
/gate/aluminiumBall/vis/setColor white

/gate/waterCylinder/daughters/name PVCBall
/gate/waterCylinder/daughters/insert sphere
/gate/PVCBall/placement/setTranslation 4.76314 2.75 -6. mm
/gate/PVCBall/geometry/setRmin 0. mm
/gate/PVCBall/geometry/setRmax 1. mm
/gate/PVCBall/setMaterial PVC
/gate/PVCBall/vis/setColor cyan

/gate/waterCylinder/daughters/name glassBall
/gate/waterCylinder/daughters/insert sphere
/gate/glassBall/placement/setTranslation -4.76314 -2.75 6. mm
/gate/glassBall/geometry/setRmin 0. mm
/gate/glassBall/geometry/setRmax 1. mm
/gate/glassBall/setMaterial Glass
/gate/glassBall/vis/setColor red

/gate/waterCylinder/daughters/name spineBoneBall
/gate/waterCylinder/daughters/insert sphere
/gate/spineBoneBall/placement/setTranslation -4.76314 2.75 6. mm
/gate/spineBoneBall/geometry/setRmin 0. mm
/gate/spineBoneBall/geometry/setRmax 1. mm
/gate/spineBoneBall/setMaterial SpineBone
/gate/spineBoneBall/vis/setColor yellow


/gate/waterCylinder/moves/insert rotation
/gate/waterCylinder/rotation/setSpeed 1. deg/s
/gate/waterCylinder/rotation/setAxis 0 0 1

###########
# PHYSICS #
###########
##############
# EM PROCESS #
##############
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel PenelopeModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-

/gate/physics/addProcess MultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized


#############
# DIGITIZER #
#############
/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 0 keV
/gate/digitizer/convertor/verbose 0
/gate/digitizer/verbose 0


##################
# INITIALIZATION #
##################
/gate/run/initialize

##############
# SOURCE GPS #
##############
/gate/source/addSource xraygun
/gate/source/verbose 0
/gate/source/xraygun/setActivity 3500. becquerel
/gate/source/xraygun/gps/verbose 0
/gate/source/xraygun/gps/particle gamma
/gate/source/xraygun/gps/energytype Arb
/gate/source/xraygun/gps/histname arb
/gate/source/xraygun/gps/emin 10.00 keV
/gate/source/xraygun/gps/emax 40.00 keV
/gate/source/xraygun/gps/histpoint  0.0100  7
/gate/source/xraygun/gps/histpoint  0.0102  4
/gate/source/xraygun/gps/histpoint  0.0104  4
/gate/source/xraygun/gps/histpoint  0.0105  4
/gate/source/xraygun/gps/histpoint  0.0106  6
/gate/source/xraygun/gps/histpoint  0.0107  3
/gate/source/xraygun/gps/histpoint  0.0108  6
/gate/source/xraygun/gps/histpoint  0.0109  5
/gate/source/xraygun/gps/histpoint  0.0110  7
/gate/source/xraygun/gps/histpoint  0.0112  6
/gate/source/xraygun/gps/histpoint  0.0114  8
/gate/source/xraygun/gps/histpoint  0.0115  7
/gate/source/xraygun/gps/histpoint  0.0116  7
/gate/source/xraygun/gps/histpoint  0.0117  10
/gate/source/xraygun/gps/histpoint  0.0118  9
/gate/source/xraygun/gps/histpoint  0.0119  11
/gate/source/xraygun/gps/histpoint  0.0120  11
/gate/source/xraygun/gps/histpoint  0.0122  8
/gate/source/xraygun/gps/histpoint  0.0123  7
/gate/source/xraygun/gps/histpoint  0.0124  10
/gate/source/xraygun/gps/histpoint  0.0125  15
/gate/source/xraygun/gps/histpoint  0.0126  19
/gate/source/xraygun/gps/histpoint  0.0127  17
/gate/source/xraygun/gps/histpoint  0.0128  18
/gate/source/xraygun/gps/histpoint  0.0129  21
/gate/source/xraygun/gps/histpoint  0.0130  24
/gate/source/xraygun/gps/histpoint  0.0132  19
/gate/source/xraygun/gps/histpoint  0.0133  33
/gate/source/xraygun/gps/histpoint  0.0134  32
/gate/source/xraygun/gps/histpoint  0.0135  34
/gate/source/xraygun/gps/histpoint  0.0136  36
/gate/source/xraygun/gps/histpoint  0.0137  34
/gate/source/xraygun/gps/histpoint  0.0138  33
/gate/source/xraygun/gps/histpoint  0.0139  38
/gate/source/xraygun/gps/histpoint  0.0140  34
/gate/source/xraygun/gps/histpoint  0.0142  32
/gate/source/xraygun/gps/histpoint  0.0143  42
/gate/source/xraygun/gps/histpoint  0.0144  37
/gate/source/xraygun/gps/histpoint  0.0145  39
/gate/source/xraygun/gps/histpoint  0.0146  49
/gate/source/xraygun/gps/histpoint  0.0147  53
/gate/source/xraygun/gps/histpoint  0.0148  48
/gate/source/xraygun/gps/histpoint  0.0149  50
/gate/source/xraygun/gps/histpoint  0.0150  62
/gate/source/xraygun/gps/histpoint  0.0152  69
/gate/source/xraygun/gps/histpoint  0.0153  51
/gate/source/xraygun/gps/histpoint  0.0154  63
/gate/source/xraygun/gps/histpoint  0.0155  80
/gate/source/xraygun/gps/histpoint  0.0156  64
/gate/source/xraygun/gps/histpoint  0.0157  77
/gate/source/xraygun/gps/histpoint  0.0158  90
/gate/source/xraygun/gps/histpoint  0.0159  73
/gate/source/xraygun/gps/histpoint  0.0160  81
/gate/source/xraygun/gps/histpoint  0.0162  74
/gate/source/xraygun/gps/histpoint  0.0163  80
/gate/source/xraygun/gps/histpoint  0.0164  81
/gate/source/xraygun/gps/histpoint  0.0165  88
/gate/source/xraygun/gps/histpoint  0.0166  97
/gate/source/xraygun/gps/histpoint  0.0167  94
/gate/source/xraygun/gps/histpoint  0.0168  104
/gate/source/xraygun/gps/histpoint  0.0169  151
/gate/source/xraygun/gps/histpoint  0.0170  287
/gate/source/xraygun/gps/histpoint  0.0172  1056
/gate/source/xraygun/gps/histpoint  0.0173  1489
/gate/source/xraygun/gps/histpoint  0.0174  1676
/gate/source/xraygun/gps/histpoint  0.0175  1520
/gate/source/xraygun/gps/histpoint  0.0176  1055
/gate/source/xraygun/gps/histpoint  0.0177  550
/gate/source/xraygun/gps/histpoint  0.0178  296
/gate/source/xraygun/gps/histpoint  0.0179  159
/gate/source/xraygun/gps/histpoint  0.0180  105
/gate/source/xraygun/gps/histpoint  0.0182  111
/gate/source/xraygun/gps/histpoint  0.0183  114
/gate/source/xraygun/gps/histpoint  0.0184  112
/gate/source/xraygun/gps/histpoint  0.0185  129
/gate/source/xraygun/gps/histpoint  0.0186  112
/gate/source/xraygun/gps/histpoint  0.0187  119
/gate/source/xraygun/gps/histpoint  0.0188  121
/gate/source/xraygun/gps/histpoint  0.0189  91
/gate/source/xraygun/gps/histpoint  0.0190  66
/gate/source/xraygun/gps/histpoint  0.0192  15
/gate/source/xraygun/gps/histpoint  0.0193  7
/gate/source/xraygun/gps/histpoint  0.0194  6
/gate/source/xraygun/gps/histpoint  0.0195  6
/gate/source/xraygun/gps/histpoint  0.0196  9
/gate/source/xraygun/gps/histpoint  0.0197  10
/gate/source/xraygun/gps/histpoint  0.0198  4
/gate/source/xraygun/gps/histpoint  0.0199  6
/gate/source/xraygun/gps/histpoint  0.0200  3
/gate/source/xraygun/gps/histpoint  0.0202  1
/gate/source/xraygun/gps/histpoint  0.0203  1
/gate/source/xraygun/gps/histpoint  0.0204  1
/gate/source/xraygun/gps/histpoint  0.0205  0
/gate/source/xraygun/gps/histpoint  0.0206  0
/gate/source/xraygun/gps/histpoint  0.0207  0
/gate/source/xraygun/gps/histpoint  0.0208  2
/gate/source/xraygun/gps/histpoint  0.0209  0
/gate/source/xraygun/gps/histpoint  0.0210  0
/gate/source/xraygun/gps/histpoint  0.0212  1
/gate/source/xraygun/gps/histpoint  0.0214  0
/gate/source/xraygun/gps/histpoint  0.0215  0
/gate/source/xraygun/gps/histpoint  0.0216  1
/gate/source/xraygun/gps/histpoint  0.0217  0
/gate/source/xraygun/gps/histpoint  0.0218  2
/gate/source/xraygun/gps/histpoint  0.0219  1
/gate/source/xraygun/gps/histpoint  0.0220  1
/gate/source/xraygun/gps/histpoint  0.0222  2
/gate/source/xraygun/gps/histpoint  0.0224  1
/gate/source/xraygun/gps/histpoint  0.0225  2
/gate/source/xraygun/gps/histpoint  0.0226  1
/gate/source/xraygun/gps/histpoint  0.0227  0
/gate/source/xraygun/gps/histpoint  0.0228  1
/gate/source/xraygun/gps/histpoint  0.0229  1
/gate/source/xraygun/gps/histpoint  0.0230  3
/gate/source/xraygun/gps/histpoint  0.0232  3
/gate/source/xraygun/gps/histpoint  0.0233  3
/gate/source/xraygun/gps/histpoint  0.0234  3
/gate/source/xraygun/gps/histpoint  0.0235  1
/gate/source/xraygun/gps/histpoint  0.0236  3
/gate/source/xraygun/gps/histpoint  0.0237  3
/gate/source/xraygun/gps/histpoint  0.0238  2
/gate/source/xraygun/gps/histpoint  0.0239  1
/gate/source/xraygun/gps/histpoint  0.0240  3
/gate/source/xraygun/gps/histpoint  0.0242  6
/gate/source/xraygun/gps/histpoint  0.0243  4
/gate/source/xraygun/gps/histpoint  0.0244  1
/gate/source/xraygun/gps/histpoint  0.0245  1
/gate/source/xraygun/gps/histpoint  0.0246  2
/gate/source/xraygun/gps/histpoint  0.0247  7
/gate/source/xraygun/gps/histpoint  0.0248  6
/gate/source/xraygun/gps/histpoint  0.0249  4
/gate/source/xraygun/gps/histpoint  0.0250  8
/gate/source/xraygun/gps/histpoint  0.0252  5
/gate/source/xraygun/gps/histpoint  0.0254  3
/gate/source/xraygun/gps/histpoint  0.0255  2
/gate/source/xraygun/gps/histpoint  0.0256  6
/gate/source/xraygun/gps/histpoint  0.0257  5
/gate/source/xraygun/gps/histpoint  0.0258  6
/gate/source/xraygun/gps/histpoint  0.0259  2
/gate/source/xraygun/gps/histpoint  0.0260  9
/gate/source/xraygun/gps/histpoint  0.0262  5
/gate/source/xraygun/gps/histpoint  0.0264  6
/gate/source/xraygun/gps/histpoint  0.0265  5
/gate/source/xraygun/gps/histpoint  0.0266  6
/gate/source/xraygun/gps/histpoint  0.0267  7
/gate/source/xraygun/gps/histpoint  0.0268  8
/gate/source/xraygun/gps/histpoint  0.0269  4
/gate/source/xraygun/gps/histpoint  0.0270  7
/gate/source/xraygun/gps/histpoint  0.0272  7
/gate/source/xraygun/gps/histpoint  0.0274  8
/gate/source/xraygun/gps/histpoint  0.0275  9
/gate/source/xraygun/gps/histpoint  0.0276  8
/gate/source/xraygun/gps/histpoint  0.0277  7
/gate/source/xraygun/gps/histpoint  0.0278  7
/gate/source/xraygun/gps/histpoint  0.0279  10
/gate/source/xraygun/gps/histpoint  0.0280  15
/gate/source/xraygun/gps/histpoint  0.0282  3
/gate/source/xraygun/gps/histpoint  0.0283  11
/gate/source/xraygun/gps/histpoint  0.0284  10
/gate/source/xraygun/gps/histpoint  0.0285  9
/gate/source/xraygun/gps/histpoint  0.0286  11
/gate/source/xraygun/gps/histpoint  0.0287  8
/gate/source/xraygun/gps/histpoint  0.0288  6
/gate/source/xraygun/gps/histpoint  0.0289  9
/gate/source/xraygun/gps/histpoint  0.0290  14
/gate/source/xraygun/gps/histpoint  0.0292  6
/gate/source/xraygun/gps/histpoint  0.0293  8
/gate/source/xraygun/gps/histpoint  0.0294  8
/gate/source/xraygun/gps/histpoint  0.0295  9
/gate/source/xraygun/gps/histpoint  0.0296  9
/gate/source/xraygun/gps/histpoint  0.0297  8
/gate/source/xraygun/gps/histpoint  0.0298  5
/gate/source/xraygun/gps/histpoint  0.0299  7
/gate/source/xraygun/gps/histpoint  0.0300  8
/gate/source/xraygun/gps/histpoint  0.0302  11
/gate/source/xraygun/gps/histpoint  0.0304  12
/gate/source/xraygun/gps/histpoint  0.0305  10
/gate/source/xraygun/gps/histpoint  0.0306  12
/gate/source/xraygun/gps/histpoint  0.0307  11
/gate/source/xraygun/gps/histpoint  0.0308  14
/gate/source/xraygun/gps/histpoint  0.0309  8
/gate/source/xraygun/gps/histpoint  0.0310  15
/gate/source/xraygun/gps/histpoint  0.0312  12
/gate/source/xraygun/gps/histpoint  0.0314  12
/gate/source/xraygun/gps/histpoint  0.0315  19
/gate/source/xraygun/gps/histpoint  0.0316  13
/gate/source/xraygun/gps/histpoint  0.0317  16
/gate/source/xraygun/gps/histpoint  0.0318  10
/gate/source/xraygun/gps/histpoint  0.0319  8
/gate/source/xraygun/gps/histpoint  0.0320  11
/gate/source/xraygun/gps/histpoint  0.0321  8
/gate/source/xraygun/gps/histpoint  0.0322  11
/gate/source/xraygun/gps/histpoint  0.0324  15
/gate/source/xraygun/gps/histpoint  0.0325  11
/gate/source/xraygun/gps/histpoint  0.0326  9
/gate/source/xraygun/gps/histpoint  0.0327  13
/gate/source/xraygun/gps/histpoint  0.0328  9
/gate/source/xraygun/gps/histpoint  0.0329  11
/gate/source/xraygun/gps/histpoint  0.0330  11
/gate/source/xraygun/gps/histpoint  0.0332  11
/gate/source/xraygun/gps/histpoint  0.0333  14
/gate/source/xraygun/gps/histpoint  0.0334  12
/gate/source/xraygun/gps/histpoint  0.0335  10
/gate/source/xraygun/gps/histpoint  0.0336  11
/gate/source/xraygun/gps/histpoint  0.0337  9
/gate/source/xraygun/gps/histpoint  0.0338  12
/gate/source/xraygun/gps/histpoint  0.0339  6
/gate/source/xraygun/gps/histpoint  0.0340  13
/gate/source/xraygun/gps/histpoint  0.0342  12
/gate/source/xraygun/gps/histpoint  0.0343  8
/gate/source/xraygun/gps/histpoint  0.0344  13
/gate/source/xraygun/gps/histpoint  0.0345  14
/gate/source/xraygun/gps/histpoint  0.0346  11
/gate/source/xraygun/gps/histpoint  0.0347  12
/gate/source/xraygun/gps/histpoint  0.0348  13
/gate/source/xraygun/gps/histpoint  0.0349  9
/gate/source/xraygun/gps/histpoint  0.0350  8
/gate/source/xraygun/gps/histpoint  0.0352  11
/gate/source/xraygun/gps/histpoint  0.0354  10
/gate/source/xraygun/gps/histpoint  0.0355  12
/gate/source/xraygun/gps/histpoint  0.0356  18
/gate/source/xraygun/gps/histpoint  0.0357  11
/gate/source/xraygun/gps/histpoint  0.0358  14
/gate/source/xraygun/gps/histpoint  0.0359  12
/gate/source/xraygun/gps/histpoint  0.0360  17
/gate/source/xraygun/gps/histpoint  0.0362  14
/gate/source/xraygun/gps/histpoint  0.0364  10
/gate/source/xraygun/gps/histpoint  0.0365  7
/gate/source/xraygun/gps/histpoint  0.0366  15
/gate/source/xraygun/gps/histpoint  0.0367  14
/gate/source/xraygun/gps/histpoint  0.0368  15
/gate/source/xraygun/gps/histpoint  0.0369  11
/gate/source/xraygun/gps/histpoint  0.0370  11
/gate/source/xraygun/gps/histpoint  0.0372  13
/gate/source/xraygun/gps/histpoint  0.0374  5
/gate/source/xraygun/gps/histpoint  0.0375  12
/gate/source/xraygun/gps/histpoint  0.0376  11
/gate/source/xraygun/gps/histpoint  0.0377  12
/gate/source/xraygun/gps/histpoint  0.0378  15
/gate/source/xraygun/gps/histpoint  0.0379  9
/gate/source/xraygun/gps/histpoint  0.0380  10
/gate/source/xraygun/gps/histpoint  0.0382  6
/gate/source/xraygun/gps/histpoint  0.0384  6
/gate/source/xraygun/gps/histpoint  0.0385  6
/gate/source/xraygun/gps/histpoint  0.0386  7
/gate/source/xraygun/gps/histpoint  0.0387  5
/gate/source/xraygun/gps/histpoint  0.0388  5
/gate/source/xraygun/gps/histpoint  0.0389  4
/gate/source/xraygun/gps/histpoint  0.0390  6
/gate/source/xraygun/gps/histpoint  0.0392  9
/gate/source/xraygun/gps/histpoint  0.0394  5
/gate/source/xraygun/gps/histpoint  0.0395  4
/gate/source/xraygun/gps/histpoint  0.0396  0
/gate/source/xraygun/gps/histpoint  0.0397  0
/gate/source/xraygun/gps/histpoint  0.0398  0
/gate/source/xraygun/gps/histpoint  0.0399  0
/gate/source/xraygun/gps/histpoint  0.0400  0 
/gate/source/xraygun/gps/arbint Lin
/gate/source/xraygun/gps/type Plane
/gate/source/xraygun/gps/shape Rectangle
/gate/source/xraygun/gps/halfx 0.025 mm
/gate/source/xraygun/gps/halfy 0.025 mm
/gate/source/xraygun/gps/mintheta 0  deg
/gate/source/xraygun/gps/maxtheta  6.8 deg
/gate/source/xraygun/gps/centre 0. 0. -15.0 cm
/gate/source/xraygun/gps/angtype iso
/gate/source/list
##########
# OUTPUT #
##########


/gate/output/tree/enable
/gate/output/tree/addFileName output/data.npy
#/gate/output/tree/hits/enable

/gate/output/tree/addCollection Singles

#########
# ASCII #
#########
/gate/output/ascii/setOutFileVoxelFlag false
/gate/output/ascii/setOutFileHitsFlag false

############
# CT Image #
############
/gate/output/imageCT/enable
/gate/output/imageCT/verbose 0
/gate/output/imageCT/setFileName output/benchmarkFastCT
/gate/output/imageCT/numFastPixelX 10
/gate/output/imageCT/numFastPixelY 10
/gate/output/imageCT/numFastPixelZ   1

/gate/random/setEngineSeed auto

#############
# VERBOSITY #
#############
/control/verbose 0
/run/verbose 0
/run/particle/verbose 0

/run/particle/dumpCutValues
/event/verbose 0
/tracking/verbose 0
/tracking/verbose 0

/gate/generator/verbose 0
/gate/source/verbose 0
/run/particle/verbose 0




###############
# ACQUISITION #
###############
################################
# ACQUISITION for 1 projection #
################################
#/gate/application/setTimeSlice     90. s
#/gate/application/setTimeStart     0.  s
#/gate/application/setTimeStop      180. s

####################################
# ACQUISITION with 360 projections #
####################################
/gate/application/setTimeSlice     1. s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      360. s

/gate/application/startDAQ


