/gate/actor/addActor  EnergySpectrumActor  MyActor
/gate/actor/MyActor/save                  output/Energy.root
/gate/actor/MyActor/attachTo              detector
/gate/actor/MyActor/saveAsText		  false
/gate/actor/MyActor/enableFluenceTrackSpectrum   false
/gate/actor/MyActor/enableEdepSpectrum       false
/gate/actor/MyActor/enableElossHisto         false
/gate/actor/MyActor/enableEdepHisto          true
/gate/actor/MyActor/energyLossHisto/setEmin              0 eV
/gate/actor/MyActor/energyLossHisto/setEmax              2000 keV
/gate/actor/MyActor/energyLossHisto/setNumberOfBins      4000