/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle       gamma
/gate/source/mybeam/gps/ene/mono       100 keV
/gate/source/mybeam/gps/ene/type       Mono
/gate/source/mybeam/gps/pos/halfx      0.1 cm
/gate/source/mybeam/gps/pos/halfy      0.1 cm
/gate/source/mybeam/gps/pos/centre     0 0 -310 cm
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/direction      0 0 1
/gate/source/mybeam/gps/ang/type       focused
/gate/source/mybeam/gps/ang/focuspoint 0 0 -300 cm

