#=====================================================
# VERBOSITY
#=====================================================

/control/execute                        mac/verbose.mac

#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase      data/GateMaterials.db

# World
/gate/world/geometry/setXLength         1 m
/gate/world/geometry/setYLength         1 m
/gate/world/geometry/setZLength         1 m
/gate/world/setMaterial                 Air

/gate/world/daughters/name              scanner
/gate/world/daughters/insert            box
/gate/scanner/geometry/setXLength         1 m
/gate/scanner/geometry/setYLength         1 m
/gate/scanner/geometry/setZLength         1 m
/gate/scanner/setMaterial                 Air



# EPID
/gate/scanner/daughters/name              EPID
/gate/scanner/daughters/insert            box
/gate/EPID/geometry/setXLength       40 cm
/gate/EPID/geometry/setYLength       40 cm
/gate/EPID/geometry/setZLength       1 mm
/gate/EPID/placement/setTranslation  0 0 45 cm
/gate/EPID/setMaterial               GSO
/gate/EPID/vis/setColor              magenta

#

# Water Box
/gate/scanner/daughters/name              waterbox
/gate/scanner/daughters/insert            box
/gate/waterbox/geometry/setXLength      40 cm
/gate/waterbox/geometry/setYLength      40 cm
/gate/waterbox/geometry/setZLength      40 cm
/gate/waterbox/placement/setTranslation 0 0 0 cm
/gate/waterbox/setMaterial              Water
/gate/waterbox/vis/setVisible           1
/gate/waterbox/vis/setColor             blue





#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList            emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 10 mm
/gate/physics/Electron/SetCutInRegion   world 10 mm
/gate/physics/Positron/SetCutInRegion   world 10 mm

/gate/physics/Gamma/SetCutInRegion      waterbox 0.1 mm
/gate/physics/Electron/SetCutInRegion   waterbox 0.1 mm
/gate/physics/Positron/SetCutInRegion   waterbox 0.1 mm

#/gate/physics/displayCuts

#=====================================================
# OUTPUTS
#=====================================================

#-----------------------------------------------------
# Water Box outputs
#-----------------------------------------------------


#/control/execute                        mac/actors.mac






/gate/systems/scanner/level1/attach     EPID
/gate/systems/scanner/level2/attach     waterbox

#/gate/EPID/attachCrystalSD
/gate/waterbox/attachCrystalSD


#-----------------------------------------------------
# EPID (system) outputs
#-----------------------------------------------------

# List of interactions - ASCII or binary format
#/gate/output/ascii/enable
#/gate/output/ascii/setFileName                output/list-
#/gate/output/ascii/setOutFileHitsFlag         1
#/gate/output/ascii/setOutFileSinglesFlag      0
/gate/output/binary/enable
/gate/output/binary/setFileName               output/list-
/gate/output/binary/setOutFileHitsFlag        1
/gate/output/binary/setOutFileSinglesFlag     0

# Tree of interactions - ROOT and NumPy format
/gate/output/tree/enable
/gate/output/tree/addFileName                 output/tree_water.npy
/gate/output/tree/addFileName                 output/tree_water.root
/gate/output/tree/hits/enable

#-----------------------------------------------------
# Simulation statistics
#-----------------------------------------------------

/gate/actor/addActor                          SimulationStatisticActor stat
/gate/actor/stat/save                         output/simu-stats.txt
/gate/actor/stat/saveEveryNSeconds            30

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource                  mybeam gps
/gate/source/mybeam/gps/particle        gamma
/gate/source/mybeam/gps/pos/type        Beam
/gate/source/mybeam/gps/pos/rot1        0 1 0
/gate/source/mybeam/gps/pos/rot2        1 0 0
/gate/source/mybeam/gps/pos/shape       Circle
/gate/source/mybeam/gps/pos/centre      0 0 -40 cm
/gate/source/mybeam/gps/pos/sigma_x     3 mm
/gate/source/mybeam/gps/pos/sigma_y     3 mm
/gate/source/mybeam/gps/ene/mono        10 MeV
/gate/source/mybeam/gps/ene/type        Gauss
/gate/source/mybeam/gps/ene/sigma       1.0 MeV
/gate/source/mybeam/gps/direction       0 0 1

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

#=====================================================
# START BEAMS
#=====================================================

# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName                  MersenneTwister
/gate/random/setEngineSeed                  12

/gate/application/setTotalNumberOfPrimaries 1e5
/gate/application/start

